// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohkpdufmckdpzbxtxqud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9oa3BkdWZtY2tkcHpieHR4cXVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzOTI0MzEsImV4cCI6MjA2NDk2ODQzMX0.88dqqSOoYpHvTANl7ST-if-ryRS0OdB_w6CVGX-TGEE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);